composer.json, features/creating_simple_order.feature, spec/Factory/OrderFactorySpec.php, src/Controller/SelectNewOrderCustomerAction.php, src/Factory/OrderFactory.php, src/Form/Type/NewOrderCustomerCreateType.php, src/Resources/config/app/admin_routing.yml, src/Resources/config/services.xml, src/Resources/translations/messages.en.yml, src/Resources/views/orderSelectCustomer.html.twig, tests/Application/app/AppKernel.php, tests/Behat/Context/Admin/ManagingOrdersContext.php, tests/Behat/Page/Admin/NewOrderCustomerPage.php
Customer is created for a new order if does not already exist. The drawback is that it's created even if the order creation would not be created after all.
=> Creating simple order for new customer

features/creating_order_with_online_payment.feature, spec/EventListener/PaymentLinkCreationListenerSpec.php, spec/Provider/PaymentTokenProviderSpec.php, spec/Sender/OrderPaymentLinkSenderSpec.php, src/EventListener/PaymentLinkCreationListener.php, src/Provider/PaymentTokenProvider.php, src/Provider/PaymentTokenProviderInterface.php, src/Resources/config/app/config.yml, src/Resources/config/app/routing.yml, src/Resources/config/services.xml, src/Resources/translations/messages.en.yml, src/Resources/views/Emails/orderCreated.html.twig, src/Resources/views/SyliusAdminBundle/Order/Show/_payment.html.twig, src/Sender/OrderPaymentLinkSender.php, src/Sender/OrderPaymentLinkSenderInterface.php, tests/Application/app/Resources/SyliusAdminBundle/views/Order/Show/_payment.html.twig, tests/Application/app/config/routing.yml, tests/Behat/Context/Admin/ManagingOrdersContext.php, tests/Behat/Page/Admin/OrderShowPage.php, tests/Behat/Page/Admin/OrderShowPageInterface.php, tests/Behat/Resources/services.xml
Based on https://github.com/Sylius/AdminOrderCreationPlugin/pull/4
=> Creating order with online payment

src/Resources/translations/messages.en.yml, src/Resources/views/orderCreate.html.twig, tests/Behat/Page/Admin/OrderCreatePage.php
Based on https://github.com/Sylius/AdminOrderCreationPlugin/pull/7
Before:
After:
=> Ui improvements

src/Resources/translations/messages.en.yml, src/Resources/views/orderSelectCustomer.html.twig, tests/Behat/Page/Admin/NewOrderCustomerPage.php
=> Ui improvements in customer select/create form

src/Doctrine/ORM/CustomerRepository.php, src/Form/Type/CustomerAutocompleteChoiceType.php, src/Form/Type/NewOrderCustomerSelectType.php, src/Resources/config/app/config.yml, src/Resources/config/app/routing.yml, src/Resources/views/orderSelectCustomer.html.twig, src/Resources/views/orderSelectCustomerTheme.html.twig, tests/Behat/Page/Admin/NewOrderCustomerPage.php
The UI is not so fabulous as it was, because SemanticUI is a 🥔sometimes :/
=> Autocomplete customer select

src/Doctrine/ORM/CustomerRepository.php, src/Doctrine/ORM/CustomerRepositoryInterface.php, src/Form/Type/CustomerAutocompleteChoiceType.php, src/Form/Type/NewOrderCustomerSelectType.php, src/Resources/config/app/routing.yml
Mentioned in https://github.com/Sylius/AdminOrderCreationPlugin/pull/19#pullrequestreview-127828593
=> Autocomplete customer select fixes

src/Doctrine/ORM/ProductVariantRepository.php, src/Doctrine/ORM/ProductVariantRepositoryInterface.php, src/Form/Type/OrderItemType.php, src/Resources/config/app/ajax.yml, src/Resources/config/app/config.yml, src/Resources/config/app/routing.yml, src/Resources/views/orderCreate.html.twig, src/Resources/views/orderItemCollectionTheme.html.twig, tests/Behat/Context/Admin/ManagingOrdersContext.php, tests/Behat/Page/Admin/NewOrderCustomerPage.php, tests/Behat/Page/Admin/OrderCreatePage.php, tests/Behat/Page/Admin/OrderCreatePageInterface.php, tests/Behat/Resources/services.xml, tests/Behat/Service/AutoCompleteSelector.php
=> Autocomplete variant name

README.md, migrations/Version20180626065141.php, src/Resources/config/app/routing.yml, src/Resources/config/services.xml
- installation process description fixes
- not decorating factories and uses them explicitly in routing
- missing migration generated
=> Maintenance fixes

features/reordering/applying_promotions_during_reordering_placed_order.feature, features/reordering/reordering_placed_order_with_different_data.feature, features/reordering/reordering_placed_order_with_modified_total_price.feature, features/reordering/reordering_placed_order_with_modified_unit_price.feature, features/reordering/reordering_placed_order_without_changes.feature, tests/Behat/Resources/suites.yml, tests/Behat/Resources/suites/admin_reordering.yml
`@reordering` tags is the same as in https://github.com/Sylius/CustomerReorderPlugin
=> Change reordering tag due to possible conflict

tests/Behat/Element/Admin/OrderCreateFormElement.php
We'll see will it work... We must definitely think about lowering the amount of JS tests in this plugin (which can be hard, but not impossible)
=> Give tests a little bit more time

src/Form/Type/NewOrderType.php
=> [Admin] Billing address is not required during order creation

features/creating_order/going_back_from_order_preview.feature, features/creating_order/modifying_order_total.feature, features/creating_order/modifying_unit_price.feature, features/reordering/reordering_placed_order_with_modified_total_price.feature, features/reordering/reordering_placed_order_with_modified_unit_price.feature, tests/Behat/Element/Admin/OrderCreateFormElement.php
=> [Behat] Enable scenarios for modifying prices during reordering

features/creating_order/creating_order_with_offline_payment.feature, spec/EventListener/PaymentLinkCreationListenerSpec.php, src/EventListener/PaymentLinkCreationListener.php, src/Form/Type/AdjustmentType.php, tests/Behat/Context/Admin/ManagingOrdersContext.php
Fixes https://github.com/Sylius/AdminOrderCreationPlugin/issues/11
=> Don't set payment link for offline payment

.travis.yml, features/creating_order/creating_order_with_multiple_items.feature
=> Run all the tests

features/creating_order/previewing_order_before_creation.feature, src/Form/Type/CurrencyCodeChoiceType.php, src/Form/Type/NewOrderType.php, src/Resources/config/services.xml, src/Resources/views/Order/Create/_form.html.twig, tests/Behat/Context/Admin/ManagingOrdersContext.php, tests/Behat/Element/Admin/OrderCreateFormElement.php, tests/Behat/Element/Admin/OrderCreateFormElementInterface.php, tests/Behat/Page/Admin/OrderPreviewPage.php, tests/Behat/Page/Admin/OrderPreviewPageInterface.php
=> Currency added to create new order form

src/Controller/ProvideAvailableShippingMethodsAction.php
=> Fixed infinite spinner for items that do not require shipping

composer.json, phpstan.neon, src/Factory/OrderFactory.php
In order to do that I had to manually update phpstan to (0.10)
=> Added PHPStan Webmozart Extension

src/Resources/views/Order/preview.html.twig
It kinda fixes the issue #89 but this is not the optimal solution.
=> Added error messages from order creation page

src/Resources/views/Order/selectCustomer.html.twig
Fixes #74
The reason why I made a function for it might become clear when I add a pull request for the customer select by id.
=> Moving the error message after the input field

src/Resources/views/Order/selectCustomer.html.twig
=> Remove not necessary jquery import

composer.json, features/creating_order/modifying_item_price.feature, features/reordering/reordering_placed_order_with_promotions.feature, src/Resources/views/Order/Show/_summary.html.twig, src/Resources/views/SyliusAdminBundle/Order/Show/Summary/_item.html.twig, src/Resources/views/SyliusAdminBundle/Order/Show/Summary/_totals.html.twig, src/Resources/views/SyliusAdminBundle/Order/Show/_payment.html.twig, tests/Application/templates/bundles/SyliusAdminBundle/Order/Show/Summary/_item.html.twig, tests/Application/templates/bundles/SyliusAdminBundle/Order/Show/Summary/_totals.html.twig, tests/Application/templates/bundles/SyliusAdminBundle/Order/Show/_payment.html.twig, tests/Behat/Page/Admin/OrderPreviewPage.php
=> [Admin][Order] Make templates compatible with Sylius alpha

composer.json
I've also removed unneeded `"minimum-stability": "dev",`
=> Use stable Sylius 1.6

.travis.yml, composer.json, src/Resources/config/app/config.yml
The same changes as in https://github.com/Sylius/InvoicingPlugin/pull/116
=> Allow to overwrite order created email template

src/Resources/views/Order/create.html.twig
This call has probably been forgotten after a debugging session.
=> Remove unexpected call to console.log

src/Resources/config/app/ajax.yml
I have around 720 products.
And this little change did a big change in response time.
=> Use Autocomplete serialization group (gain -75% of number of SQL requests)

composer.json
As mentioned by @aleho in #170.
=> Really allow for Sylius 1.9 and 1.10

.github/workflows/build.yml, UPGRADE.md, composer.json, src/ReorderProcessing/CompositeReorderProcessor.php, tests/Application/.env, tests/Application/.env.test, tests/Application/Kernel.php, tests/Application/config/bundles.php
- Drop support for PHP 7.4
- Bump up support for Symfony 5 to 5.4 version
- Add support for Sylius 1.11 + drop support for Sylius 1.9
=> [Maintenance] Upgrade dependencies

README.md
Migrations were removes in previous commit
=> Remove useless Migrations step from README.md

spec/Sender/OrderPaymentLinkSenderSpec.php, src/Sender/OrderPaymentLinkSender.php
Now created `Order` passed to email template to be able to render breakdown / user can see what he pays for
=> Improved: OrderPaymentLinkSender

src/Resources/views/Order/create.html.twig
We've got problem with cors errors during ajax loading as it forces http protocol instead of https, to avoid this problem for the future users We provided such a fix
=> Fix HTTP protocol for FOSJSRouting generation

.github/workflows/build.yaml, composer.json, tests/Application/Kernel.php, tests/Application/config/bundles.php
=> [Maintenance] Add PHP version to requirements + adjust Kernel and bundles configuration
